carting/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="carting:search_by_position")),
    path("text", views.search_by_text, name="search_by_text"),
    path("position", views.search_by_position, name="search_by_position"),
    path(
        "position/<uuid:root_expanded>/<uuid:expanded>",
        views.search_by_position_details,
        name="search_by_position_details",
    ),
    path("pilotage", views.pilotage_search, name="pilotage_search"),
    path(
        "proxy/wms",
        views.wms_proxy,
        kwargs={"wms_url": "https://services.data.shom.fr/INSPIRE/wms/v"},
        name="wms-proxy",
    ),
]

core/urls.py
import typing

from django.conf import settings
from django.contrib import admin
from django.urls import URLPattern, URLResolver, include, path

URL = typing.Union[URLPattern, URLResolver]
URLList = typing.List[URL]

urlpatterns: URLList = [
    path("admin/", admin.site.urls),
    path("", include(("carting.urls", "carting"), namespace="carting")),
]

if settings.DEBUG:
    urlpatterns.extend(
        [
            path("__debug__/", include("debug_toolbar.urls")),
            path("__reload__/", include("django_browser_reload.urls")),
        ]
    )

carting/models.py
from __future__ import annotations

import logging
from enum import Enum
from functools import cached_property
from typing import Iterator, NamedTuple
from xml.etree import ElementTree

import lxml.etree as ET
from django.contrib.gis.db import models
from django.db import DatabaseError
from django.utils.safestring import mark_safe
from tree_queries.models import TreeNode, TreeQuerySet

xslt_transform = ET.XSLT(ET.parse("carting/xslt/ouvrage_section_html.xslt"))


class SectionIngester(NamedTuple):
    element: ElementTree.Element
    ouvrage_name: str

    def numero(self, parent: OuvrageSection) -> str:
        return parent.numero

    def content(self) -> str:
        return ElementTree.tostring(self.element, encoding="unicode")


class AlineaIngester(SectionIngester):
    def numero(self, parent: OuvrageSection) -> str:
        return f"{parent.numero}0.{self.element.find('nmrAlinea').text}"


class FigureIngester(SectionIngester):
    def numero(self, parent: OuvrageSection) -> str:
        return self.element.find("numero").text


class ParagraphIngester(SectionIngester):
    def numero(self, parent: OuvrageSection) -> str:
        return self.element.find("titre/numero").text

    def content(self) -> str:
        return ElementTree.tostring(self.element.find("titre"), encoding="unicode")


class OuvrageIngester(SectionIngester):
    def numero(self, parent: None) -> str:
        return self.ouvrage_name

    def content(self) -> str:
        return ""


class SectionTypology(Enum):
    _ignore_ = "Definition"

    class Definition(NamedTuple):
        xpaths: list[str]
        ingester: type[SectionIngester]
        html_tag: str | None = None

    OUVRAGE = Definition(["ouvrage"], OuvrageIngester)
    CHAPTER = Definition(["chapitre"], ParagraphIngester, "h2")
    SUBCHAPTER = Definition(["sChapitre"], ParagraphIngester, "h3")
    PARAGRAPH = Definition(["para"], ParagraphIngester, "h4")
    SUBPARAGRAPH = Definition(["sPara"], ParagraphIngester, "h5")
    SUBSUBPARAGRAPH = Definition(["ssPara"], ParagraphIngester, "h6")
    ALINEA = Definition(["alinea"], AlineaIngester)
    TABLE = Definition(["tableau"], FigureIngester)
    ILLUSTRATION = Definition(["illustration"], FigureIngester)
    TOPONYME = Definition(["texte/principal", "liste/texte/principal"], SectionIngester)
    REFERENCE = Definition(
        ["texte/reference", "liste/texte/reference"], SectionIngester
    )

    @property
    def label(self) -> str:
        return self.name.capitalize()

    @property
    def xpaths(self) -> list[str]:
        return self.value.xpaths

    @property
    def html_tag(self) -> str:
        return self.value.html_tag

    @property
    def ingester(self) -> type[SectionIngester]:
        return self.value.ingester

    @classmethod
    @property
    def choices(cls) -> list[tuple[str, str]]:
        return [(member.name, member.label) for member in cls]

    @classmethod
    @property
    def paragraph_likes(cls):
        return {member for member in cls if member.ingester == ParagraphIngester}


def find_ingestable_child_elements(
    element: ElementTree.Element,
) -> Iterator[tuple[SectionTypology, ElementTree.Element]]:
    for typology in SectionTypology:
        for xpath in typology.xpaths:
            for child_element in element.iterfind(xpath):
                yield typology, child_element


class OuvrageSectionManager(models.Manager):
    def ingest_xml_subtree(
        self,
        ouvrage_name: str,
        element: ElementTree.Element,
        ouvrage_section: OuvrageSection | None = None,
    ) -> int:
        ingested = 0
        for typology, child_element in find_ingestable_child_elements(element):
            child_ouvrage_section = OuvrageSection.from_xml(
                child_element, ouvrage_section, typology, ouvrage_name
            )
            child_ouvrage_section.ingest()

            logging.info(
                "Section %s ingérée avec l'id %s",
                typology.name,
                child_ouvrage_section.bpn_id,
            )
            ingested += 1
            ingested += self.ingest_xml_subtree(
                ouvrage_name, child_element, child_ouvrage_section
            )
        return ingested


class OuvrageSection(TreeNode):
    objects = OuvrageSectionManager.from_queryset(TreeQuerySet)()

    bpn_id = models.UUIDField(primary_key=True)
    numero = models.CharField(max_length=20)
    content = models.TextField(blank=True)
    typology = models.CharField(max_length=25, choices=SectionTypology.choices)
    ouvrage_name = models.CharField(max_length=10)
    geometry = models.GeometryField(blank=True, null=True, default=None, srid=4326)

    class Meta:
        ordering = ("numero",)

    def __str__(self):
        return f"{self.numero} - {self.typology_object.label}"

    @property
    def typology_object(self) -> SectionTypology:
        return SectionTypology[self.typology]

    @classmethod
    def from_xml(
        cls,
        element: ElementTree.Element,
        parent: "OuvrageSection" | None,
        typology: SectionTypology,
        ouvrage_name: str,
    ) -> "OuvrageSection":
        ingester = typology.ingester(element, ouvrage_name)

        return cls(
            bpn_id=element.attrib["bpn_id"],
            numero=ingester.numero(parent),
            content=ingester.content(),
            typology=typology.name,
            ouvrage_name=ouvrage_name,
            parent=parent,
        )

    def ingest(self):
        self.clean_fields()

        try:
            # This raises if the instance does not exist
            self.save(
                update_fields=(
                    "numero",
                    "content",
                    "typology",
                    "ouvrage_name",
                    "parent",
                )
            )
        except DatabaseError:
            self.save()

    @cached_property
    def content_html(self):
        if not self.content:
            return ""

        inner_html = xslt_transform(ET.fromstring(self.content))

        html_tag = self.typology_object.html_tag

        if html_tag:
            # FIXME : extraire dans un templatetag django
            inner_html = f'<{html_tag} class="fr-mt-2w">{inner_html}</{html_tag}>'
        return mark_safe(inner_html)

    @property
    def should_display(self):
        return self.typology_object not in [
            SectionTypology.REFERENCE,
            SectionTypology.TOPONYME,
        ]

carting/models/s100.py
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.gis.db import models


class ISO639_3(models.TextChoices):
    FRA = "fra", "French"
    ENG = "eng", "English"


class CategoryOfText(models.TextChoices):
    """
    Classification of completeness of textual information in relation to the
    source.

    :cvar ABSTRACT_OR_SUMMARY: A statement summarizing the important
        points of a text.
    :cvar EXTRACT: An excerpt or excerpts from a text.
    :cvar FULL_TEXT: The whole text
    """

    ABSTRACT_OR_SUMMARY = "abstract or summary"
    EXTRACT = "extract"
    FULL_TEXT = "full text"


class ComplexAttributeType(models.Model):
    class Meta:
        abstract = True


class GenericComplexAttributeType(ComplexAttributeType):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.BigIntegerField()
    content_object = GenericForeignKey()

    class Meta:
        abstract = True


# class GMLObject(models.Model):
#     # FIXME : Discuter de l'algo de création automatique de l'id
#     id = models.CharField(primary_key=True, max_length=255)


class FeatureName(GenericComplexAttributeType):
    language = models.CharField(
        max_length=3,
        choices=ISO639_3.choices,
    )
    name = models.CharField(
        max_length=255, help_text="The individual name of a feature."
    )
    display_name = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.language} - {self.name}"

    # Uncomment when upgrading to django 4.2
    # class Meta:
    #     db_table_comment = "The complex attribute provides the name of an entity, "
    #     "defines the national language of the name, and provides the option to "
    #     "display the name at various system display settings."


class Information(GenericComplexAttributeType):
    language = models.CharField(
        max_length=3, choices=ISO639_3.choices, default=ISO639_3.FRA
    )
    headline = models.CharField(max_length=255, blank=True)
    text = models.TextField(blank=True)


class TextContent(GenericComplexAttributeType):
    category_of_text = models.CharField(max_length=255, choices=CategoryOfText.choices)
    information = GenericRelation(Information)


class FeatureType(models.Model):
    feature_names = GenericRelation(FeatureName)
    text_contents = GenericRelation(TextContent)
    permission_types = GenericRelation("carting.PermissionType")

    class Meta:
        abstract = True


class InformationType(models.Model):
    feature_names = GenericRelation(FeatureName)

    class Meta:
        abstract = True

carting/views.py
import json
from uuid import UUID

import requests
from django.contrib.gis import geos
from django.core.serializers import serialize
from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.decorators.http import require_GET

from carting.models import OuvrageSection, SectionTypology
from s127.models import PilotageDistrict, PilotBoardingPlace

SAINT_MALO_BBOX = "-3.15, 47.32, -1.65, 49.14"


@require_GET
def pilotage_search(request: HttpRequest) -> HttpResponse:
    qs_bbox = request.GET.get("bbox", SAINT_MALO_BBOX)
    qs_bbox = [float(coordinate) for coordinate in qs_bbox.split(",")]
    bbox = geos.Polygon.from_bbox(qs_bbox)

    pilotage_districts = PilotageDistrict.objects.filter(geometry__bboverlaps=bbox)
    boarding_places = PilotBoardingPlace.objects.filter(
        pilotservice__pilotage_district__in=pilotage_districts
    )
    geojson = serialize(
        "geojson", (*pilotage_districts, *boarding_places), id_field="geojson_id"
    )

    return render(
        request,
        "carting/pilotage_search.html",
        {
            "scroll_snap": True,
            "geojson": geojson,
            "bbox": json.dumps(qs_bbox),
            "pilotage_districts": pilotage_districts,
        },
    )


@require_GET
def search_by_position(request: HttpRequest) -> HttpResponse:
    zoom_level = float(request.GET.get("zoom", 1))

    qs_bbox = request.GET.get("bbox", SAINT_MALO_BBOX)
    qs_bbox = [float(coordinate) for coordinate in qs_bbox.split(",")]
    bbox = geos.Polygon.from_bbox(qs_bbox)

    allowed_typologies = SectionTypology.paragraph_likes
    if zoom_level < 7:
        allowed_typologies = [SectionTypology.CHAPTER]

    sections = (
        OuvrageSection.objects.filter(geometry__bboverlaps=bbox)
        # FIXME : A geometry is not excluded by filter below 75f7dbbd-c0b4-456f-bc10-19f72f89608b
        .exclude(geometry__contains_properly=bbox).filter(
            typology__in=[x.name for x in allowed_typologies]
        )
    )

    geojson = serialize("geojson", (s for s in sections if s.geometry))

    return render(
        request,
        "carting/search_by_position.html",
        {
            "scroll_snap": True,
            "geojson": geojson,
            "bbox": json.dumps(qs_bbox),
            "zoom_level": zoom_level,
            "sections": sections,
        },
    )


@require_GET
def search_by_position_details(
    request: HttpRequest, root_expanded: UUID, expanded: UUID
) -> HttpResponse:
    zoom_level = float(request.GET.get("zoom", 1))

    qs_bbox = request.GET.get("bbox", SAINT_MALO_BBOX)
    qs_bbox = [float(coordinate) for coordinate in qs_bbox.split(",")]

    expanded_section = OuvrageSection.objects.prefetch_related("children").get(
        pk=expanded
    )

    to_serialize = [expanded_section, *expanded_section.children.all()]
    geojson = serialize("geojson", (s for s in to_serialize if s.geometry))

    return render(
        request,
        "carting/search_by_position.html",
        {
            "scroll_snap": True,
            "geojson": geojson,
            "bbox": json.dumps(qs_bbox),
            "zoom_level": zoom_level,
            "root_expanded": root_expanded,
            "expanded": expanded,
            "expanded_section": expanded_section,
        },
    )


# FIXME : Les sections commençant par '0.' ne devraient pas être affichées (pas de géométrie attachée); les illustrations en '0.' sont mal ordonnées
@require_GET
def search_by_text(request: HttpRequest) -> HttpResponse:
    search = request.GET.get("search", "")

    if not search:
        return redirect(reverse("carting:search_by_text") + "?search=4.1.")

    if not search.endswith("."):
        return redirect(reverse("carting:search_by_text") + f"?search={search}.")

    ouvrage, _, numero = search.rpartition("/")
    if not numero:
        return render(
            request,
            "carting/search_by_text.html",
        )
    allowed_typologies = SectionTypology.paragraph_likes.union(
        {SectionTypology.OUVRAGE}
    )
    sections = OuvrageSection.objects.filter(
        typology__in=[x.name for x in allowed_typologies]
    ).with_tree_fields()
    if ouvrage:
        sections = sections.filter(ouvrage_name=ouvrage)
    try:
        # FIXME: 4.2. get() returned more than one OuvrageSection -- it returned 2!
        section = sections.get(numero=numero)
    except OuvrageSection.DoesNotExist:
        raise Http404(
            "Probably we won't fix it : No OuvrageSection matches the given query."
        )
    except OuvrageSection.MultipleObjectsReturned:
        raise Http404(
            "Probably we won't fix it : Multiple OuvrageSections match the given query."
        )
    sections = [*section.ancestors(), *section.descendants(include_self=True)]

    geojson = serialize("geojson", (s for s in sections if s.geometry))
    return render(
        request,
        "carting/search_by_text.html",
        {
            "sections": sections,
            "geojson": geojson,
            "search_tree_depth": section.tree_depth,
            "search": search,
        },
    )


# Needed until https://github.com/betagouv/SPPNautInterface/issues/185 is closed
@require_GET
def wms_proxy(request, wms_url):
    response = requests.get(url=wms_url, params=request.GET.dict())
    http_response = HttpResponse(response)
    headers_to_forward = ["Content-Type", "Content-Length"]
    for header in headers_to_forward:
        if header in response.headers:
            http_response.headers[header] = response.headers[header]
    return http_response

templates/carting/index.html
{% extends "layout/base.html" %}

{% load static %}

{% block page_title %}Carting{% endblock%}

{% block extra_css %}
<link rel="stylesheet" href="{% static "carting.css" %}">
{% endblock %}

{% block js %}
<script type="module" src="{% static "carting.js" %}"></script>
{% endblock %}

{% block main %}
<div class="fr-container--fluid">
    <div
        data-controller="map"
        data-map-wms-url-value="{% url 'carting:wms-proxy' %}"
        data-action="
            ol:select->map#selectSectionInText
            wms:featureInfoFetched->map#showFeaturePopin
            hashchange@window->map#selectSectionInMapFromHash
            hashchange@window->map#closeFeaturePopin
        "
        class="
            fr-grid-row fr-m-1w
            sn-bg-white
        "
    >
        <script type="application/geojson" data-map-target="geojson">
            {{ geojson|safe }}
        </script>
        <div class="fr-col-12 fr-col-md-7">
            <div
                id="map"
                data-map-target="map"
                class="
                    sn-max-h-screen sn-h-full sn-w-full sn-sticky sn-top-0
                    fr-p-1w
                "
            >
            </div>
        </div>
        <div class="
                sn-relative
                fr-col-12 fr-col-md-5 fr-p-1w
            "
        >
            <div
                data-controller="popin"
                data-map-target="featurePopin"
                aria-hidden="true"
                class="
                    sn-flex aria-hidden:sn-hidden sn-sticky sn-top-0 sn-h-screen sn-flex-col sn-z-10
                    fr-p-1w fr-background-default--grey
                "
            >
                <button
                    data-action="popin#close"
                    class="fr-mb-1w fr-btn fr-btn--icon-right fr-btn--tertiary fr-icon-close-circle-fill"
                >
                    Fermer
                </button>
                <div
                    data-popin-target="content"
                    class="sn-overflow-y-auto sn-overscroll-contain"
                ></div>
            </div>
            <form>
                <div class="fr-search-bar" role="search">
                    <input
                        class="fr-input"
                        placeholder="Cherche par ouvrage/section, ex : z99/4.2.2."
                        type="search"
                        value="{{search|default_if_none:''}}"
                        name="search"
                    >
                    <button class="fr-btn" title="Rechercher">
                        Rechercher
                    </button>
                </div>
            </form>
            <hr/>
            <div>
                {% for section in sections %}
                    {% if section.should_display %}
                        <div
                            id="{{section.pk}}"
                            class="sn-flex sn-gap-1w sn-mb-1w sn-max-w-readable target:sn-bg-info-975-active sn-scroll-mt-[20vh]"
                        >
                            <span class="sn-min-w-5w">
                                {% if section.geometry and section.tree_depth >= search_tree_depth %}
                                    <a
                                        href="#{{ section.pk }}"
                                        class="fr-btn fr-btn--tertiary-no-outline fr-icon-map-pin-2-line"
                                        data-action="
                                            mouseenter->map#highlightSectionInMap
                                            mouseleave->map#unhighlightSectionInMap
                                        "
                                    >
                                        Montrer sur la carte
                                    </a>
                                {% endif %}
                            </span>
                            <div>
                                {{ section.content_html }}
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/carting/pilotage_search.html
{% extends "layout/base.html" %}

{% load static %}

{% block page_title %}Carting - Recherche position{% endblock%}

{% block extra_css %}
<link rel="stylesheet" href="{% static "carting.css" %}">
{% endblock %}

{% block js %}
<script type="module" src="{% static "carting.js" %}"></script>
{% endblock %}

{% block main %}
<div
    class="
        fr-container--fluid
        sn-snap-always sn-snap-start
    "
>
    <div
        data-controller="map"
        data-map-wms-url-value="{% url 'carting:wms-proxy' %}"
        data-map-bbox-value="{{ bbox }}"
        data-action="
            ol:select->map#selectSectionInText
            ol:changed->map#updateBboxInUrl
            wms:featureInfoFetched->map#showFeaturePopin
            hashchange@window->map#selectSectionInMapFromHash
            hashchange@window->map#closeFeaturePopin
        "
        class="
            fr-grid-row fr-m-1w
            sn-bg-white
        "
    >
        <div class="fr-col-12 fr-col-md-7">
            <div
                id="map"
                data-map-target="map"
                class="
                    sn-h-[98vh] sn-w-full
                    fr-p-1w
                "
            >
            </div>
            <div class="
                    fr-text--xs
                    sn-text-center
                "
            >
                Astuce : Appuyez sur la touche Majuscule tout en cliquant sur une balise pour en voir la photo et les détails
            </div>
        </div>
        <div class="
                sn-relative
                fr-col-12 fr-col-md-5 fr-p-1w
            "
        >
            {% include 'carting/partial/layer_popin.html' %}

            <turbo-frame
                id="pilotage_districts"
                data-map-target="turboframe"
                data-turbo-action="advance"
                class="
                    sn-block sn-h-screen sn-overflow-auto sn-overscroll-contain sn-px-1v sn-pb-1v
                    aria-busy:sn-opacity-50 sn-transition-opacity sn-ease-in aria-busy:sn-delay-150
                "
            >
                <script type="application/geojson" data-map-target="geojson">
                    {{ geojson|safe }}
                </script>
                {% for pilotage_district in pilotage_districts %}
                    {% include 'carting/cards/pilotage_district.html' %}
                {% endfor %}
            </turbo-frame>
        </div>
    </div>
</div>
{% endblock %}

templates/carting/search_by_position.html
{% extends "layout/base.html" %}

{% load static %}

{% block page_title %}Carting - Recherche position{% endblock%}

{% block extra_css %}
<link rel="stylesheet" href="{% static "carting.css" %}">
{% endblock %}

{% block js %}
<script type="module" src="{% static "carting.js" %}"></script>
{% endblock %}

{% block main %}
<div
    class="
        fr-container--fluid
        sn-snap-always sn-snap-start
    "
>
    <div
        data-controller="map"
        data-map-wms-url-value="{% url 'carting:wms-proxy' %}"
        data-map-bbox-value="{{ bbox }}"
        data-action="
            ol:select->map#selectSectionInText
            ol:changed->map#updateBboxInUrl
            wms:featureInfoFetched->map#showFeaturePopin
            hashchange@window->map#selectSectionInMapFromHash
            hashchange@window->map#closeFeaturePopin
        "
        class="
            fr-grid-row fr-m-1w
            sn-bg-white
        "
    >
        <div class="fr-col-12 fr-col-md-7">
            <div
                id="map"
                data-map-target="map"
                class="
                    sn-h-[98vh] sn-w-full
                    fr-p-1w
                "
            >
            </div>
            <div class="
                    fr-text--xs
                    sn-text-center
                "
            >
                Astuce : Appuyez sur la touche Majuscule tout en cliquant sur une balise pour en voir la photo et les détails
            </div>
        </div>
        <div class="
                sn-relative
                fr-col-12 fr-col-md-5 fr-p-1w
            "
        >
            {% include 'carting/partial/layer_popin.html' %}

            <turbo-frame
                id="sections"
                data-map-target="turboframe"
                data-turbo-action="advance"
                class="
                    sn-block sn-h-screen sn-overflow-auto sn-overscroll-contain sn-px-1v sn-pb-1v
                    aria-busy:sn-opacity-50 sn-transition-opacity sn-ease-in aria-busy:sn-delay-150
                "
            >
                <script type="application/geojson" data-map-target="geojson">
                    {{ geojson|safe }}
                </script>
                {% if expanded %}
                    <div class="sn-sticky sn-top-0 sn-bg-white sn-z-10">
                        <a
                            {% if expanded_section.pk == root_expanded %}
                                href="{% url 'carting:search_by_position' %}?{{request.GET.urlencode}}"
                            {% else %}
                                href="{% url 'carting:search_by_position_details' root_expanded=root_expanded expanded=expanded_section.parent.pk %}?{{request.GET.urlencode}}"
                            {% endif %}
                            class="fr-mb-1w fr-btn fr-btn--icon-left fr-btn--secondary fr-icon-arrow-left-line"
                        >
                            Retour
                        </a>
                    </div>
                    {% if expanded_section %}
                        {% include 'carting/cards/title.html' with section=expanded_section %}
                    {% endif %}
                    {% for section in expanded_section.children.all %}
                        {% if section.typology == "ALINEA" %}
                            {% ifchanged section.typology %}
                                <div class="sn-m-2w">
                            {% endifchanged %}

                            {% include 'carting/cards/alinea.html' %}

                            {% if forloop.last %}
                                </div>
                            {% endif %}
                        {% else %}
                            {% ifchanged section.typology %}
                                {% if not forloop.first %}
                                    </div>
                                {% endif %}
                            {% endifchanged %}

                            {% include 'carting/cards/title.html' %}
                        {% endif %}
                    {% endfor %}
                {% else %}
                    {% for section in sections %}
                        {% include 'carting/cards/title.html' %}
                    {% endfor %}
                {% endif %}
            </turbo-frame>
        </div>
    </div>
</div>
{% endblock %}

templates/carting/search_by_text.html
{% extends "layout/base.html" %}

{% load static %}

{% block page_title %}Carting - Recherche texte{% endblock%}

{% block extra_css %}
<link rel="stylesheet" href="{% static "carting.css" %}">
{% endblock %}

{% block js %}
<script type="module" src="{% static "carting.js" %}"></script>
{% endblock %}

{% block main %}
<div class="fr-container--fluid">
    <div
        data-controller="map"
        data-map-wms-url-value="{% url 'carting:wms-proxy' %}"
        data-action="
            ol:select->map#selectSectionInText
            wms:featureInfoFetched->map#showFeaturePopin
            hashchange@window->map#selectSectionInMapFromHash
            hashchange@window->map#closeFeaturePopin
        "
        class="
            fr-grid-row fr-m-1w
            sn-bg-white
        "
    >
        <script type="application/geojson" data-map-target="geojson">
            {{ geojson|safe }}
        </script>
        <div class="fr-col-12 fr-col-md-7">
            <div
                id="map"
                data-map-target="map"
                class="
                    sn-max-h-screen sn-h-full sn-w-full sn-sticky sn-top-0
                    fr-p-1w
                "
            >
            </div>
        </div>
        <div class="
                sn-relative
                fr-col-12 fr-col-md-5 fr-p-1w
            "
        >
            {% include 'carting/partial/layer_popin.html' %}

            <form>
                <div class="fr-search-bar" role="search">
                    <input
                        class="fr-input"
                        placeholder="Cherche par ouvrage/section, ex : z99/4.2.2."
                        type="search"
                        value="{{search|default_if_none:''}}"
                        name="search"
                    >
                    <button class="fr-btn" title="Rechercher">
                        Rechercher
                    </button>
                </div>
            </form>
            <hr/>
            <div>
                {% for section in sections %}
                    {% if section.should_display %}
                        <div
                            id="{{section.pk}}"
                            class="sn-flex sn-gap-1w sn-mb-1w sn-max-w-readable target:sn-bg-info-975-active sn-scroll-mt-[20vh]"
                        >
                            <span class="sn-min-w-5w">
                                {% if section.geometry and section.tree_depth >= search_tree_depth %}
                                    <a
                                        href="#{{ section.pk }}"
                                        class="fr-btn fr-btn--tertiary-no-outline fr-icon-map-pin-2-line"
                                        data-action="
                                            mouseenter->map#highlightSectionInMap
                                            mouseleave->map#unhighlightSectionInMap
                                        "
                                    >
                                        Montrer sur la carte
                                    </a>
                                {% endif %}
                            </span>
                            <div>
                                {{ section.content_html }}
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}